name: Docker Multi-Arch build and push

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: fifaty/jdsign

jobs:
  build-and-push-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64]

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker AMD64 image
      run: |
        docker buildx create --name builder
        docker buildx use builder
        docker buildx build --platform linux/amd64 --push -t $IMAGE_NAME:amd64 .

  build-and-push-arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [arm64]

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: QEMU setup
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      shell: bash

    - name: Build the Docker ARM64 image
      run: |
        docker buildx create --name builder
        docker buildx use builder
        docker buildx build --platform linux/arm64 --push -t $IMAGE_NAME:arm64 .

  build-and-push-manifest:
    runs-on: ubuntu-latest

    needs: [build-and-push-amd64, build-and-push-arm64]

    steps:
    - uses: docker/setup-buildx-action@v1

    - name: Combine and Push the Docker Manifest
      run: |
        docker buildx create --name builder
        docker buildx use builder
        docker buildx build --platform linux/amd64,linux/arm64 --push --manifest $IMAGE_NAME:latest --no-cache --pull $IMAGE_NAME:amd64 $IMAGE_NAME:arm64
        docker buildx create --name builder
      shell: bash
