name: Docker Multi-Arch build and push
on:
  push:
    branches:
      - main
env:
  DOCKER_CLI_EXPERIMENTAL: enabled    # 启用实验性功能
  IMAGE_NAME: fifaty/jdsign
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2    # 使用构建和推送操作，不需要手动拉取和推送
      with:
        context: .
        push: true
        platform: linux/amd64,linux/arm64/v8  # 构建不同架构的 Docker 镜像
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:{{.Tag}}-{{.OS}}-{{.Arch}}  # 显示 tag 名称，以帮助识别镜像所属平台架构
