name: Docker Multi-Arch build and push
on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: fifaty/jdsign
jobs:
  build-and-push-amd64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker AMD64 image
      run: docker build -t $IMAGE_NAME:amd64 .
      shell: bash
    - name: Push the Docker AMD64 image to Docker Hub
      run: docker push $IMAGE_NAME:amd64
      shell: bash
  build-and-push-arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [arm64]
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: QEMU setup
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      shell: bash
    - name: Build the Docker ARM64 image
      run: docker build -t $IMAGE_NAME:arm64 .
      shell: bash
    - name: Push the Docker ARM64 image to Docker Hub
      run: docker push $IMAGE_NAME:arm64
      shell: bash
  build-and-push-manifest:
    needs: [build-and-push-amd64, build-and-push-arm64]
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Create and push Docker Manifest
      run: |
        docker manifest create $IMAGE_NAME:latest $IMAGE_NAME:amd64 $IMAGE_NAME:arm64
        docker manifest push $IMAGE_NAME:latest
      shell: bash
